version: '2.0'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
